name: Conteo Pipeline

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ../backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run tests with coverage
        run: npm run test:coverage

      - Upload coverage report:
        uses: actions/upload-artifact@v2
        with:
          name: backend-coverage-report
          path: ../backend/coverage

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ../frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run frntend build
        run: npm run build
